name: Build Installers
on:
  push:
    paths:
      - '.github/workflows/build-installers.yml'
      - 'version.properties'
      - 'bluej/build.gradle'
      - 'greenfoot/build.gradle'
      - 'bluej/package/build.xml'
      - 'bluej/package/greenfoot-build.xml'
  workflow_dispatch:
jobs:
  Build-Windows-Installers:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.java_version }}
          java-package: jdk
          architecture: x64
      - name: Install choco packages
        run: |
          choco install wixtoolset -r --no-progress
          choco install msys2 -r --no-progress
          choco install mingw -r --no-progress
          choco install sed -r --no-progress
          choco install wget -r --no-progress
          choco install ant -r --no-progress
      - name: Check install locations
        run: |
          dir C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin
          dir 'C:/Program Files/'
          dir 'C:/Program Files (x86)/'
          dir 'C:/Program Files (x86)/WiX Toolset v3.11/bin'
      - name: Install JavaFX and build
        run: |
          cd ${{ github.workspace }}
          mkdir javafx && cd javafx && bash ../download-javafx.sh ${{ env.javafx_version }} win && cd ..
          $propfile = 'tools.properties'
          $java_home_forward = $env:JAVA_HOME -replace '\\', '/'
          $workspace_forward = $PWD -replace '\\', '/'
          (Get-Content $propfile) -replace 'mingw_root=.*', "mingw_root=C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64" | Set-Content $propfile
          (Get-Content $propfile) -replace 'wix_bin=.*', "wix_bin=C:/Program Files (x86)/WiX Toolset v3.11/bin" | Set-Content $propfile
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@859c33240bd026ce8d5f711f5adcc65c2f8eafc1
      - name: Gradle Build and Test
        uses: gradle/gradle-build-action@0842a550d10f5211be8c8295f6888889e1fca291
        with:
          arguments: :bluej:packageBlueJWindows :greenfoot:packageGreenfootWindows --info --stacktrace --no-daemon          
      - name: Archive BlueJ Windows installers
        uses: actions/upload-artifact@v3
        with:
          name: bluej-installers-windows
          path: |
            bluej/package/BlueJ-windows*.msi
            bluej/package/BlueJ-windows*.zip
      - name: Archive Greenfoot Windows installers
        uses: actions/upload-artifact@v3
        with:
          name: greenfoot-installers
          path: |
              bluej/package/Greenfoot-windows*.msi
              bluej/package/Greenfoot-windows*.zip
  Build-Ubuntu-Installers:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.java_version }}
          java-package: jdk
          architecture: x64
      - name: Install packages
        run: |
          sudo apt install fakeroot
      - name: Check install locations
        run: |
          ls $JAVA_HOME
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@859c33240bd026ce8d5f711f5adcc65c2f8eafc1
      - name: Gradle Build and Test
        uses: gradle/gradle-build-action@0842a550d10f5211be8c8295f6888889e1fca291
        with:
          arguments: :bluej:packageBlueJLinux :greenfoot:packageGreenfootLinux --info --stacktrace --no-daemon
      - name: Archive BlueJ Ubuntu installers
        uses: actions/upload-artifact@v3
        with:
          name: bluej-installers-other
          path: |
            bluej/package/BlueJ-linux*.deb
            bluej/package/BlueJ-generic*.jar
            bluej/package/BlueJ-source*.zip
      - name: Archive Greenfoot Ubuntu installers
        uses: actions/upload-artifact@v3
        with:
          name: greenfoot-installers
          path: |
            bluej/package/Greenfoot-linux*.deb
            bluej/package/Greenfoot-generic*.jar
            bluej/package/Greenfoot-source*.zip

  Build-Mac-Installers:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.java_version }}
          java-package: jdk
          architecture: x64
      - name: Check install locations
        run: |
          ls $JAVA_HOME
      - name: Install JavaFX and build
        run: |
          cd ${{ github.workspace }}
          echo 'ant_exe=ant' > tools.properties
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@859c33240bd026ce8d5f711f5adcc65c2f8eafc1
      - name: Gradle Build and Test
        uses: gradle/gradle-build-action@0842a550d10f5211be8c8295f6888889e1fca291
        with:
          arguments: :bluej:packageBlueJMac :greenfoot:packageGreenfootMac --info --stacktrace --no-daemon
      - name: Archive BlueJ Mac installers
        uses: actions/upload-artifact@v3
        with:
          name: bluej-installers-mac
          path: |
            bluej/package/BlueJ-mac*.zip
      - name: Archive Greenfoot Mac installers
        uses: actions/upload-artifact@v3
        with:
          name: greenfoot-installers
          path: |
            bluej/package/Greenfoot-mac*.zip
  
       
